version: '3'
services:
  elasticsearch:
    user: $USER
    image: elasticsearch:7.11.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      # - cluster.initial_master_nodes[0]=localhost
      - cluster.name=meone-search-engine
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-credentials=true
      # - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      # - http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /root/backup:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  # elasticsearch2:
  #   user: $USER
  #   image: elasticsearch:7.11.2
  #   container_name: elasticsearch2
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - http.cors.enabled=true
  #     - http.cors.allow-origin=*
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=elasticsearch"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - /root/db/elasticsearch/backup:/usr/share/elasticsearch/data
  #   networks:
  #     - esnet
  # elasticsearch3:
  #   user: $USER
  #   image: elasticsearch:7.11.2
  #   container_name: elasticsearch3
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - http.cors.enabled=true
  #     - http.cors.allow-origin=*
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=elasticsearch"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - /root/db/elasticsearch/backup:/usr/share/elasticsearch/data
  #   networks:
  #     - esnet

  kibana:
    image: 'kibana:7.11.2'
    container_name: kibana
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - esnet

  # headPlugin:
  #   image: 'mobz/elasticsearch-head:5'
  #   container_name: head
  #   ports:
  #     - '9100:9100'
  #   networks:
  #     - esnet

networks:
  esnet: