version: '3'
services:
  databasePostgresql:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: tuanz
      POSTGRES_DB: dbone  
    ports:
      - "5432:5432"
    volumes:
      - ./backup:/var/lib/postgresql/data
    networks: 
      - dbnet

networks: 
  dbnet:

# volumes: 
#     pgdata:


# =========== CLI Sync DB To Local
# rsync -avzh root@165.232.175.212:/home/db/postgresql/backup /Users/tuan/Desktop/bgg/
